{
 "title": "KServe metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(rest_server_requests_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Inference Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(model_infer_request_duration_sum[5m]) / rate(model_infer_request_duration_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(model_infer_request_success_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rest_server_requests_in_progress",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(model_infer_request_failure_total[5m]) / rate(model_infer_request_duration_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}