apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mlflow-db
spec:
  capacity:
    storage: 1Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mlflow-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mlflow-db
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
