apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mlflow-db
spec:
  capacity:
    storage: 1Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mlflow-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mlflow-db
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-server
spec:
  selector:
    app: mlflow-server
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
---
# NodePort Service for external access to MLflow UI
apiVersion: v1
kind: Service
metadata:
  name: mlflow-server-nodeport
spec:
  selector:
    app: mlflow-server
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server
  labels:
    app: mlflow-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-server
  template:
    metadata:
      labels:
        app: mlflow-server
    spec:
      containers:
        - name: mlflow-server-container
          image: mlflow-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: mlflow-db-storage
              mountPath: /mlflow
          envFrom:
            - configMapRef:
                name: minio-config
            - secretRef:
                name: minio-credentials
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      volumes:
        - name: mlflow-db-storage
          persistentVolumeClaim:
            claimName: pvc-mlflow-db
