apiVersion: v1
kind: PersistentVolume
metadata:
  name: mlflow-pv
  labels:
    app: mlflow-server
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /tmp/mlflow-data
    type: DirectoryOrCreate
