apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server
  labels:
    app: mlflow-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-server
  template:
    metadata:
      labels:
        app: mlflow-server
    spec:
      containers:
        - name: mlflow-server-container
          image: mlflow-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: mlflow-db-storage
              mountPath: /mlflow
          envFrom:
            - configMapRef:
                name: minio-config
            - secretRef:
                name: minio-credentials
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      volumes:
        - name: mlflow-db-storage
          persistentVolumeClaim:
            claimName: pvc-mlflow-db
