apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server
  labels:
    app: mlflow-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-server
  template:
    metadata:
      labels:
        app: mlflow-server
    spec:
      containers:
        - name: mlflow-server-container
          image: mlflow-server-image:latest
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: mlflow-db-storage
              mountPath: /mlflow
          env:
            - name: MLFLOW_S3_ENDPOINT_URL
              value: http://minio.minio.svc.cluster.local:9000
            - name: AWS_ACCESS_KEY_ID
              value: minioadmin
            - name: AWS_SECRET_ACCESS_KEY
              value: minioadmin
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      volumes:
        - name: mlflow-db-storage
          persistentVolumeClaim:
            claimName: pvc-mlflow-db
